[package]
name = "ofborg"
version = "0.1.1"
authors = ["Graham Christensen <graham@grahamc.com>"]
include = ["Cargo.toml", "Cargo.lock", "src", "test-srcs", "build.rs"]
build = "build.rs"


[dependencies]
log = "= 0.3.8"
env_logger = "= 0.4.3"
# amqp = { path = "./rust-amqp/" } # for testing patches
amqp = { git = "https://github.com/grahamc/rust-amqp.git" }
md5 = "0.3.5"
uuid = { version = "0.4", features = ["v4"] }
fs2 = "0.4.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempfile = "2.2.0"
hubcaps = { git = "https://github.com/grahamc/hubcaps.git" }
# hubcaps = { path = "./hubcaps/" } # for testing patches
hyper = "0.10.*"
hyper-native-tls = "0.2.4"
lru-cache = "0.1.1"

#[patch.crates-io]
#amq-proto = { path = "rust-amq-proto" }